"""
SUPABASE
"""

CONST_SUPABASE_IMAGE_CACHE_TABLE = "image_cache"
CONST_SUPABASE_STRAIN_IMAGES_BUCKET = "strain-images"
CONST_SUPABASE_STRAIN_IMAGES_EXPANDED_FOLDER = "expanded"
CONST_SUPABASE_STRAIN_IMAGES_THUMBNAIL_FOLDER = "thumbnail"

"""
    IMAGE FETCHING
"""
CONST_STRAIN_IMAGES_THUMBNAIL_RESOLUTION = (156, 156)
CONST_STRAIN_IMAGES_EXPANDED_RESOLUTION = (400, 400)
CONST_RESOLUTION_TO_SUPABASE_STRAIN_IMAGES_FOLDER = {
    CONST_STRAIN_IMAGES_THUMBNAIL_RESOLUTION: CONST_SUPABASE_STRAIN_IMAGES_THUMBNAIL_FOLDER,
    CONST_STRAIN_IMAGES_EXPANDED_RESOLUTION: CONST_SUPABASE_STRAIN_IMAGES_EXPANDED_FOLDER,
}

MAX_RETRIES = 10
