name: Fetch inventories, compare against DB, and update DB tables and buckets
on:
  workflow_dispatch:
  schedule:
     - cron: '0 */6 * * *'
jobs:
  contract-tests:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create virtual environment
      run: python3 -m venv .venv
    - name: Install dependencies
      run: .venv/bin/pip install -r requirements/inventory_fetching_requirements.txt
    - name: Run contract tests
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PYTHONPATH: ${{ github.workspace }}
      run: .venv/bin/pytest tests/api/contract_tests.py -v -o log_cli=true -o log_cli_level=INFO

  run-inventory:
    runs-on: self-hosted
    needs: contract-tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create virtual environment
      run: python3 -m venv .venv
    - name: Install dependencies
      run: .venv/bin/pip install -r requirements/inventory_fetching_requirements.txt
    - name: Run script
      env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PYTHONPATH: ${{ github.workspace }}
      run: .venv/bin/python inventory/fetch_inventories_from_api.py
    - name: Upload execution logs
      uses: actions/upload-artifact@v4
      with:
        name: execution_logs
        path: execution_logs.log
