name: Notify subscribers

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Fetch inventories, compare against DB, and update DB tables and buckets"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: "3.12.6"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run notifier
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: python -m watcher.main
