name: Persist images of new strains to the Supabase bucket
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: "3.12.6"

      - name: Install dependencies
        run: pip install -r requirements/image_fetching_requirements.txt

      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PYTHONPATH: ${{ github.workspace }}
        run: python images/fetch_images_from_api.py
      - name: Upload execution logs
        uses: actions/upload-artifact@v4
        with:
          name: execution_logs
          path: execution_logs.log
